import { Link } from 'react-router-dom';
import { AS_OF_TEXT, brand, manifest } from '@/lib/data';
import { Logo } from '@/components/Layout';

export const REPO = `https://github.com/${manifest.github_account}/${manifest.slug}`;

export default function About() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-8">
      <h1 className="text-3xl sm:text-4xl">About this site</h1>
      <p className="mt-3 font-semibold" data-testid="venue">{manifest.venue}</p>
      <p className="mt-1"><span className="bx-asof">Current as of {AS_OF_TEXT}</span></p>
      <div className="bx-prose mt-6 grid gap-4">
        <div className="flex items-center gap-4"><Logo height={56} /></div>
        <h2 className="text-2xl">Who wrote the report</h2>
        <p>The <em>{manifest.title}</em> is written by <strong>{brand.organisation}</strong> of Huntsville, Alabama, in its role as {manifest.report.role}. This site shows version {manifest.report.version}: the {manifest.report.based_on}, after a claim-by-claim check against its cited sources on 3 October 2026. It supersedes the June 2025 edition ({manifest.report.supersedes}).</p>
        <h2 className="text-2xl">What it is, and what it is not</h2>
        <p>It is a <strong>draft for review</strong>. It has not been approved by Little Orange Fish, and on approval it will be published at {manifest.report.intended_home.replace(/, on approval$/, '')}. It is not a position of the North Alabama Mental Health Coalition, of any of its members, or of anyone else; it contains no clinical guidance; and it has not been peer reviewed.</p>
        <h2 className="text-2xl">How the site was made</h2>
        <p>The report's own note on method and the use of AI is in its front section: <Link to="/read#b-B0007">“A note on method and AI”</Link>. The source summaries, the claims ledger, the change log, the open items, the glossary, the primers and the map data were prepared with Claude for this site; the <Link to="/methods">Methods</Link> page gives the counts and lists what is still missing. The site was generated by {manifest.builder.name} {manifest.builder.version} ({manifest.builder.date}).</p>
        <h2 className="text-2xl">Permissions</h2>
        <p>{manifest.permissions.text}</p>
        {manifest.permissions.figures && <p>{manifest.permissions.figures}</p>}
        <h2 className="text-2xl">Report an error</h2>
        <p>If a sentence, a number, a source or a map value is wrong, please <a href={`${REPO}/issues/new?template=report-an-error.md`} target="_blank" rel="noreferrer">open an issue on the site's repository ↗</a> with the page or block id (for example B0141, shown in the address when you follow a link to a passage), what is wrong, and the source that shows it. Or write to {brand.organisation}: <a href={`mailto:${brand.email}`}>{brand.email}</a>.</p>
        <h2 className="text-2xl">Contact</h2>
        <p>{brand.organisation} · {brand.address} · <a href={`mailto:${brand.email}`}>{brand.email}</a> · {brand.website}</p>
        <p className="italic">{brand.tagline}</p>
      </div>
    </div>
  );
}
